### ISSUE TITLE
Empty strings are treated by the compiler as a string of two double quotes 

### ISSUE THREAD

**Issue by simon6433c** [michael-lehn/abc-llvm#1]
#### Description
Two double quotes directly after another are interpreted by the compiler as a string of two double quotes instead of an empty string.

I will call them strings for convenience reasons, although they are actually pointers to an ```u8```.
```type String : -> u8```

Expected behavior: ```""``` should be interpreted as if there is nothing in the string.
Actual behavior: ```""``` is interpreted like the string ```"\"\""```.

This appears to be an bug either in the parser or in the pre-processor. 

#### To Reproduce
The following code segment is used to analyze the strings and to make the reproducibility simpler.

``` abc
@ <stdio.hdr>

// Type aliases for better readability
type Char : u8;
type String : -> Char;

// Returns the length of a String
fn strlen (str : String) : size_t {
    local length : size_t = 0;
    for (; *str != 0; ++str, ++length) {;} // Explicit empty statement
    return length;
}

// Analyzes a String by printing it out together with its length.
fn analyzeString (string : String) {
    local length : size_t = strlen(string);
    printf("The String '%s' is %zu Char(s) long.\n", string, length);
}
```

In the following example the ```emptyString``` is analyzed and it will be printed to the console that the string has a length of 2 and the content is ```""``` (exact output: ```The String '""' is 2 Char(s) long.```).

``` abc
fn main () {
    local emptyString : String = "";
    analyzeString(emptyString);
}
```

If multiple empty strings are concatenated by the pre-processor the number of double quotes will just stack. 
The call ```analyzeString("" "" "" "");``` would output ```The String '""""""""' is 8 Char(s) long.``` on the console.

But if text is inserted into the double quotes the behavior returns to what is expected for those parts of the string concatenation.
The call ```analyzeString("" "123" "" "abc");``` would output ```The String '""123""abc' is 10 Char(s) long.``` on the console.

#### Current workaround
If a pointer to an ```u8``` with the value 0 is used, it behaves like an empty String.

``` abc
fn main () {
    local zeroValue : u8 = 0
    analyzeString(&zeroValue)
}
```

In this case the console output will be ```The String '' is 0 Char(s) long.```.

**Comment by michael-lehn** [comment]
Confirmed. Thanks for reporting!

This should be fixed with commit 58ace50.

**Comment by simon6433c** [comment]
I can confirm that the commit 58ace5095ba7ad699b5ba5c29e0ed9af57d05210 fixes the issue according to all my tests.

**Comment by michael-lehn** [comment]
Fixed
